name: pldev
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.9
  - cudatoolkit==11.3.*
  - pytorch-lightning==1.8.6
  - biopython==1.83
  - pytorch::pytorch=1.12.*
  - bioconda::cd-hit
  - scipy
  - pip:
      - deepspeed==0.12.4